name: Mine-imator Beta Render
on:
  workflow_dispatch:
    inputs:
      miobject_link:
        description: 'Render edilecek dosya'
        required: true

jobs:
  render_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dosyalari Cek
        uses: actions/checkout@v4

      - name: Wine ve Modern Grafikleri Kur
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32 xvfb libgl1 libglx-mesa0 libosmesa6 mesa-utils unzip imagemagick

      - name: Motoru ve Modeli Hazirla
        run: |
          unzip mine_motor.zip -d engine
          unzip "Atahan Brine Model_102758.zip" -d assets
          chmod -R 777 engine

      - name: Motoru Baslat ve Foto Cek
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
          export DISPLAY=:99
          export LIBGL_ALWAYS_SOFTWARE=1
          
          # Mine-imator'u arka planda baslat
          wine64 engine/Mine-imator.exe &
          
          echo "Motorun acilmasi icin 60 saniye bekleniyor..."
          sleep 60
          
          # Ekran goruntusu al (import komutu imagemagick ile gelir)
          import -window root ekran_goruntusu.png
          echo "FotoÄŸraf cekildi!"

      - name: Fotografi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: mine-imator-ekran
          path: ekran_goruntusu.png
