name: Mine-imator Beta Render
on:
  workflow_dispatch:
    inputs:
      miobject_link:
        description: 'Render edilecek dosya'
        required: true

jobs:
  render_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dosyalari Cek
        uses: actions/checkout@v4

      - name: Wine ve Grafik Kur
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32 xvfb libgl1 libglx-mesa0 libosmesa6 mesa-utils unzip

      - name: Motoru ve Modeli Hazirla
        run: |
          unzip mine_motor.zip -d engine
          # ZIP icindekileri cikariyoruz ki import kolay olsun
          unzip "Atahan Brine Model_102758.zip" -d assets
          chmod -R 777 engine

      - name: Otomatik Render Komutu (720p HD)
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
          export DISPLAY=:99
          export LIBGL_ALWAYS_SOFTWARE=1
          sleep 10
          
          # 720p ve .mp4 ayarlarini komutla geciyoruz
          # "Squared Media Animation.miobject" dosyasini hedef aliyoruz
          wine64 engine/Mine-imator.exe -render "assets/Atahan Brine Model/Squared Media Animation.miobject" -output "Atahan_Render.mp4" -res 1280 720 || echo "Render baslatilmaya calisildi"
          
          # Motorun o 1-3 dakikalik acilis ve islem suresi icin bekliyoruz
          echo "Motor calisiyor, 4 dakika sabirla bekleniyor..."
          sleep 240

      - name: Videoyu Disari Aktar
        uses: actions/upload-artifact@v4
        with:
          name: render-sonucu
          path: Atahan_Render.mp4
